apiVersion: v1
kind: Service
metadata:
  name: {{ include "gpu-isolation-operator.webhookServiceName" . }}
  namespace: {{ include "gpu-isolation-operator.namespace" . }}
  labels:
    {{- include "gpu-isolation-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: webhook-server
      protocol: TCP
      name: https
  selector:
    {{- include "gpu-isolation-operator.selectorLabels" . | nindent 4 }}
