apiVersion: v1
kind: Service
metadata:
  name: gpu-isolation-webhook-service
  namespace: gpu-isolation-system
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    app: gpu-isolation-operator
